from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import joblib
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime
import io


app = Flask(__name__)

@app.route("/")
def home():
    return "App is running successfully 🚀"

# other routes below

# Allow all origins
CORS(app, resources={r"/*": {"origins": "*"}})


# Load model safely
try:
    model = joblib.load("foods.pkl")
    print("Model loaded successfully")
except Exception as e:
    print("Model loading error:", e)


@app.route("/predict", methods=["POST"])
def predict():

    try:
        data = request.get_json()

        # Check input
        if "biscuits" not in data:
            return jsonify({"error": "Missing biscuits value"}), 400

        biscuits = float(data["biscuits"])

        # Convert to DataFrame
        input_df = pd.DataFrame([[biscuits]], columns=["Biscuits"])

        # Predict
        result = model.predict(input_df)[0]

        # Load column names (same as training)
        columns = [
    "Wheat Flour (g)",
    "Oat Flour (g)",
    "Yeast (g)",
    "Sugar (g)",
    "Butter (g)",
    "Salt (g)",
    "Ammonium (g)",
    "Water (ml)",
    "Broccoli (g)",
    "Beetroot (g)"
]


        # Create response dynamically
        response = {}

        for col, val in zip(columns, result):
            response[col] = round(val, 2)

        return jsonify(response)

    except Exception as e:

        print("Prediction error:", e)

        return jsonify({
            "error": "Internal Server Error",
            "message": str(e)
        }), 500


@app.route("/download_report", methods=["POST"])
def download_report():
    try:
        data = request.get_json()
        
        biscuits = data.get("biscuits", 0)
        ingredients = data.get("ingredients", {})
        
        # Create PDF in memory
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter
        
        # Header
        c.setFont("Helvetica-Bold", 24)
        c.setFillColor(colors.HexColor("#4CAF50"))
        c.drawString(1*inch, height - 1*inch, "Biscuit Ingredient Report")
        
        # Date
        c.setFont("Helvetica", 10)
        c.setFillColor(colors.black)
        c.drawString(1*inch, height - 1.3*inch, f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
        
        # Line separator
        c.setStrokeColor(colors.HexColor("#4CAF50"))
        c.setLineWidth(2)
        c.line(1*inch, height - 1.5*inch, width - 1*inch, height - 1.5*inch)
        
        # Number of Biscuits
        y_position = height - 2*inch
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(colors.HexColor("#333333"))
        c.drawString(1*inch, y_position, "Input:")
        
        c.setFont("Helvetica", 12)
        y_position -= 0.3*inch
        c.drawString(1.2*inch, y_position, f"Number of Biscuits: {biscuits}")
        
        # Predicted Ingredients
        y_position -= 0.6*inch
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(colors.HexColor("#333333"))
        c.drawString(1*inch, y_position, "Predicted Ingredients:")
        
        y_position -= 0.4*inch
        c.setFont("Helvetica", 11)
        
        for ingredient, value in ingredients.items():
            y_position -= 0.25*inch
            c.drawString(1.2*inch, y_position, f"{ingredient}: {value}")
            
            # Check if we need a new page
            if y_position < 1.5*inch:
                c.showPage()
                y_position = height - 1*inch
                c.setFont("Helvetica", 11)
        
        # Footer
        c.setFont("Helvetica-Oblique", 9)
        c.setFillColor(colors.grey)
        c.drawString(1*inch, 0.75*inch, "FoodTech AI - Biscuit Ingredient Predictor")
        c.drawString(1*inch, 0.5*inch, "This report was automatically generated by AI prediction system")
        
        c.save()
        buffer.seek(0)
        
        return send_file(
            buffer,
            mimetype='application/pdf',
            as_attachment=True,
            download_name=f'biscuit_report_{datetime.now().strftime("%Y%m%d_%H%M%S")}.pdf'
        )
        
    except Exception as e:
        print("Report generation error:", e)
        return jsonify({
            "error": "Report generation failed",
            "message": str(e)
        }), 500


if __name__ == "__main__":
    import os
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
